"""Render the HTTP contract from `backend/openapi.json` into readable Markdown (T-703).

    cd backend && uv run python -m tools.httpdocs           # rewrite docs/HTTP_API.md
    cd backend && uv run python -m tools.httpdocs --check   # fail if it has drifted

**Why this one is COMMITTED when every other generated artefact is gitignored.** `docs/` is the
only documentation the public repository ships -- the spec, `planning/` and `CLAUDE.md` are all
excluded -- so a reader who clones gets `backend/openapi.json` and no way to read it but raw JSON.
Committing the rendered contract is what makes the HTTP surface legible with no toolchain at all.

That trade is only safe because the file is **guarded**: `tests/test_http_docs.py` re-renders it
and fails on any difference, which is exactly the precedent `backend/openapi.json` itself sets
(R-57(2) -- committed, with a test that fails when it stops matching the app). A committed
generated file without that guard is the stale file the rest of this task is written to avoid.

**Determinism is a requirement, not a nicety.** The guard compares bytes, so anything that varies
run to run -- a timestamp, a dict iteration order, a version string -- would make the test fail on
an unchanged tree. Nothing here reads the clock, and every mapping is walked in a sorted or
document order that the source file fixes.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = REPO_ROOT / "backend" / "openapi.json"
OUTPUT_PATH = REPO_ROOT / "docs" / "HTTP_API.md"

_METHODS = ("get", "post", "put", "patch", "delete")


def _load(spec_path: Path = SPEC_PATH) -> dict[str, Any]:
    return json.loads(spec_path.read_text(encoding="utf-8"))


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _type_of(schema: dict[str, Any]) -> str:
    """A short, human type for one schema node. Not a full JSON-Schema renderer."""
    if "$ref" in schema:
        return f"[`{_ref_name(schema['$ref'])}`](#{_anchor(_ref_name(schema['$ref']))})"
    if "anyOf" in schema or "oneOf" in schema:
        parts = [_type_of(s) for s in schema.get("anyOf") or schema.get("oneOf", [])]
        # `X | null` is how an optional field arrives from Pydantic; keep it readable.
        return " \\| ".join(dict.fromkeys(parts))
    if schema.get("type") == "array":
        return f"{_type_of(schema.get('items', {}))}[]"
    if "const" in schema:
        return f"`{schema['const']}`"
    if "enum" in schema:
        return " \\| ".join(f"`{v}`" for v in schema["enum"])
    t = schema.get("type")
    if t is None:
        return "any"
    fmt = schema.get("format")
    return f"{t} ({fmt})" if fmt else str(t)


def _anchor(name: str) -> str:
    return name.lower().replace("_", "-")


def _clean(text: str | None) -> str:
    """Collapse a description to one table-safe line."""
    if not text:
        return ""
    return " ".join(text.split()).replace("|", "\\|")


def _operations(spec: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """Every operation as (METHOD, path, operation), in document order.

    Document order rather than sorted: the spec is generated by FastAPI from the router
    registration order, which groups related routes together and is stable across runs.
    """
    out = []
    for path, item in spec["paths"].items():
        for method in _METHODS:
            if method in item:
                out.append((method.upper(), path, item[method]))
    return out


def _body_line(op: dict[str, Any]) -> str:
    body = op.get("requestBody")
    if not body:
        return ""
    parts = []
    for content_type, media in sorted(body.get("content", {}).items()):
        parts.append(f"{_type_of(media.get('schema', {}))} as `{content_type}`")
    required = " (required)" if body.get("required") else " (optional)"
    return ", ".join(parts) + required


def render(spec: dict[str, Any]) -> str:
    ops = _operations(spec)
    by_tag: dict[str, list[tuple[str, str, dict[str, Any]]]] = {}
    for method, path, op in ops:
        for tag in op.get("tags") or ["untagged"]:
            by_tag.setdefault(tag, []).append((method, path, op))

    L: list[str] = []
    info = spec.get("info", {})
    L.append(f"# {info.get('title', 'HTTP API')}")
    L.append("")
    L.append(
        "**Generated from `backend/openapi.json` -- do not edit.** Regenerate with "
        "`cd backend && uv run python -m tools.httpdocs`; `tests/test_http_docs.py` fails if this "
        "file stops matching the specification, and that specification is itself checked against "
        "the running application."
    )
    L.append("")
    L.append(
        f"API version `{info.get('version', '?')}` -- "
        f"**{len(ops)} operations** across {len(spec['paths'])} paths and "
        f"{len(spec.get('components', {}).get('schemas', {}))} schemas."
    )
    L.append("")
    L.append(
        "Authentication is a bearer token on every operation marked **yes**; see "
        "[SECURITY.md](SECURITY.md) for how one is obtained and what invalidates it. Error bodies "
        "carry a stable `error_code` -- match on that, never on the prose."
    )
    L.append("")

    # ---- index ------------------------------------------------------------------------
    L.append("## Index")
    L.append("")
    L.append("| | Method | Path | Auth | Summary |")
    L.append("|---|---|---|---|---|")
    for tag in sorted(by_tag):
        for method, path, op in by_tag[tag]:
            auth = "yes" if op.get("security") else "no"
            L.append(
                f"| `{tag}` | **{method}** | [`{path}`](#{_anchor(op['operationId'])}) "
                f"| {auth} | {_clean(op.get('summary'))} |"
            )
    L.append("")

    # ---- operations -------------------------------------------------------------------
    for tag in sorted(by_tag):
        L.append(f"## `{tag}`")
        L.append("")
        for method, path, op in by_tag[tag]:
            L.append(f"### {method} {path}")
            L.append("")
            L.append(f'<a id="{_anchor(op["operationId"])}"></a>')
            L.append("")
            if op.get("summary"):
                L.append(f"{_clean(op['summary'])}")
                L.append("")
            if op.get("description"):
                L.append(_clean(op["description"]))
                L.append("")
            L.append(
                f"- **Operation id:** `{op['operationId']}`"
                + ("\n- **Authentication:** bearer token" if op.get("security") else "")
            )
            body = _body_line(op)
            if body:
                L.append(f"- **Request body:** {body}")
            L.append("")

            params = op.get("parameters") or []
            if params:
                L.append("| Parameter | In | Required | Type | Description |")
                L.append("|---|---|---|---|---|")
                for p in params:
                    L.append(
                        f"| `{p['name']}` | {p['in']} | {'yes' if p.get('required') else 'no'} "
                        f"| {_type_of(p.get('schema', {}))} | {_clean(p.get('description'))} |"
                    )
                L.append("")

            L.append("| Status | Body | Meaning |")
            L.append("|---|---|---|")
            for code in sorted(op["responses"]):
                resp = op["responses"][code]
                schema = ""
                for media in resp.get("content", {}).values():
                    schema = _type_of(media.get("schema", {}))
                    break
                L.append(f"| `{code}` | {schema or '--'} | {_clean(resp.get('description'))} |")
            L.append("")

    # ---- schemas ----------------------------------------------------------------------
    schemas = spec.get("components", {}).get("schemas", {})
    if schemas:
        L.append("## Schemas")
        L.append("")
        for name in sorted(schemas):
            s = schemas[name]
            L.append(f"### `{name}`")
            L.append("")
            L.append(f'<a id="{_anchor(name)}"></a>')
            L.append("")
            if s.get("description"):
                L.append(_clean(s["description"]))
                L.append("")
            if s.get("enum"):
                L.append("One of: " + ", ".join(f"`{v}`" for v in s["enum"]))
                L.append("")
                continue
            props = s.get("properties") or {}
            if not props:
                L.append("_No properties._")
                L.append("")
                continue
            required = set(s.get("required") or [])
            L.append("| Field | Type | Required | Description |")
            L.append("|---|---|---|---|")
            for field in sorted(props):
                p = props[field]
                L.append(
                    f"| `{field}` | {_type_of(p)} | {'yes' if field in required else 'no'} "
                    f"| {_clean(p.get('description'))} |"
                )
            L.append("")

    return "\n".join(L).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tools.httpdocs",
        description="Render the HTTP contract from openapi.json into docs/HTTP_API.md.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed file has drifted",
    )
    args = parser.parse_args(argv)

    rendered = render(_load())

    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current == rendered:
            print("httpdocs: docs/HTTP_API.md is current")
            return 0
        print(
            "httpdocs: docs/HTTP_API.md is STALE -- regenerate with"
            " `uv run python -m tools.httpdocs`",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" so the committed file is LF on every platform; the guard compares bytes and a
    # CRLF rewrite on Windows would fail it against an unchanged specification.
    OUTPUT_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"httpdocs: wrote {OUTPUT_PATH} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
