"""Create a known-good demo corpus: a user, four documents and a few answered chats (T-709).

    cd backend && uv run python -m tools.seed_demo plan          # what it would do, no writes
    cd backend && uv run python -m tools.seed_demo run --yes     # do it

**Why it drives the HTTP API rather than the database.** Every other tool here
(`tools.reembed`, `tools.acceptance`) works in-process against the ORM, and this one
deliberately does not. Seeding through `POST /api/v1/documents` means the demo corpus inherits
FR-KBM-08 dedup, the FR-ERR-02 quota, the 300 MB ceiling, R-33(5) type sniffing, the R-32 scan,
the R-24 processing lock and the whole ingestion pipeline **by construction** rather than by a
second implementation — the same argument R-63(4) used to make cloud import reuse
`upload_document`. It also means what a reviewer reproduces is what a user would have done.

The cost is that this needs a **running API and worker**, which `plan` checks for and says so.

**Repeatable, using the product's own idempotency rather than bookkeeping of its own.**
Re-running converges instead of duplicating: a second upload of identical bytes is FR-KBM-08's
`200 duplicate:true` (no job, no version burned), a second create of the demo user is a `409`,
and conversations are matched by title before being created. Nothing here deletes anything —
a seed script that can destroy a corpus is one nobody dares run twice.

**The documents are generated, never committed.** This repository contains no binary fixtures
at all: `tests/test_recognition.py` synthesises its PDFs with PyMuPDF at runtime, and this
follows it. So the corpus is reproducible byte-for-byte from source, the repo stays free of
blobs nobody can diff, and the table-bearing PDF exercises FR-ING-08's real detector rather
than a file someone once made by hand.

**The scan is skipped loudly when recognition is off, never seeded silently.** Without
`PARSER_OCR_ENABLED` *and* the `ocr` sidecar, an image-only PDF ingests to `FAILED` with
`NO_EXTRACTABLE_TEXT` (R-34) — correct behaviour, and a terrible thing to find unexplained in a
demo corpus a manual is being written against. Both switches are checked and named.

**It changes no settings and writes no configuration.** Turning recognition on is an operator
decision with its own budget arithmetic (`PARSER_OCR_BUDGET_SECONDS` + `OCR_TIMEOUT_SECONDS`
must stay under `WORKER_JOB_TIMEOUT_SECONDS`), and a seed script quietly editing `.env` would
be the worst possible place to discover that.

**Model realism.** The turns are generated by whatever `LLM_BACKEND` names. Against the real
provider the answers read like answers and carry citations, DeepEval chips and scores, which is
what `docs/` screenshots need. Under `LLM_BACKEND=fake` the wiring still runs end to end but the
prose is synthetic — fine as a smoke test, wrong as a screenshot source. `EMBEDDING_BACKEND` is
independent: with `fake` vectors retrieval still works, because R-37's sparse `ts_rank_cd` arm
carries it, and the questions below are worded to be reachable lexically for that reason.
"""

from __future__ import annotations

import argparse
import io
import sys
import time
from dataclasses import dataclass, field

import httpx

from app.config import get_settings

__all__ = ["main"]

#: Where the API is. The dev default; pass `--base-url http://localhost:8088` for the
#: containerised stack, where only the edge publishes a port (R-81(1)).
DEFAULT_BASE_URL = "http://localhost:8000"

#: How long to wait for the worker to take a document all the way to ACTIVE. Generous, because
#: an OCR page is allowed 60 s of its own and the queue may be busy.
INGEST_TIMEOUT_SECONDS = 300.0
INGEST_POLL_SECONDS = 1.5

#: A turn is ~5-6 s of model latency (R-48), and the graph's own ceiling is
#: GRAPH_NODE_TIMEOUT_SECONDS. This only has to outlast that.
TURN_TIMEOUT_SECONDS = 180.0


# --- the corpus ----------------------------------------------------------------------


@dataclass(frozen=True)
class SeedDocument:
    filename: str
    content_type: str
    build: str  # the builder's name, resolved in `_build`
    why: str  # what this document is *for*, printed by `plan`
    needs_ocr: bool = False


@dataclass(frozen=True)
class SeedChat:
    title: str
    questions: tuple[str, ...]
    why: str


DOCUMENTS: tuple[SeedDocument, ...] = (
    SeedDocument(
        "Acme_Q3_Report.pdf",
        "application/pdf",
        "table_pdf",
        "FR-ING-08 - a born-digital table, so a citation can land on a row rather than on prose",
    ),
    SeedDocument(
        "Acme_Expenses.csv",
        "text/csv",
        "expenses_csv",
        "R-34's `rows` locator, and R-35(11)'s repeated header on a split table",
    ),
    SeedDocument(
        "Acme_Security_Policy.md",
        "text/markdown",
        "policy_markdown",
        "R-34's `section` locator - a heading chain the FR-CIT-03 card can name",
    ),
    SeedDocument(
        "Acme_Signed_Invoice.pdf",
        "application/pdf",
        "scanned_pdf",
        "FR-ING-07 - image-only, reachable only through recognition",
        needs_ocr=True,
    ),
)

CHATS: tuple[SeedChat, ...] = (
    SeedChat(
        "Q3 revenue",
        ("What was the revenue for the EMEA region in Q3?",),
        "a grounded answer citing a table row",
    ),
    SeedChat(
        "Security policy",
        ("What is the password rotation policy?", "How long are audit logs retained?"),
        "a two-turn chat, so the transcript shows history and the meter has moved",
    ),
    SeedChat(
        "Travel spend",
        ("How much was spent on travel?",),
        "a citation into the CSV, on a `rows` locator",
    ),
    SeedChat(
        "Unanswerable",
        ("What is the chief executive's home address?",),
        "an abstention - FR-SYS-02's refusal, and the surface FR-MSG-09's control sits on",
    ),
)


# --- document builders ---------------------------------------------------------------
#
# PyMuPDF is already a parser dependency; nothing new is introduced. The scan technique -
# render pages, re-insert them as full-page rasters - is `tests/test_recognition.py`'s
# `make_scanned_pdf`, deliberately not imported: a shipped tool must not depend on the suite.


def _table_pdf() -> bytes:
    import pymupdf

    doc = pymupdf.open()
    page = doc.new_page()
    page.insert_text((72, 90), "Acme Corporation - Q3 Report", fontsize=16)
    page.insert_text(
        (72, 120),
        "Revenue grew across every region in the third quarter.",
        fontsize=11,
    )
    rows = [
        ("Region", "Revenue (USD)", "Growth"),
        ("EMEA", "4,812,000", "12%"),
        ("Americas", "7,304,500", "9%"),
        ("APAC", "2,145,750", "21%"),
    ]
    top, left, row_h, col_w = 160, 72, 22, 140
    for r, row in enumerate(rows):
        for c, cell in enumerate(row):
            rect = pymupdf.Rect(
                left + c * col_w, top + r * row_h, left + (c + 1) * col_w, top + (r + 1) * row_h
            )
            page.draw_rect(rect, width=0.6)
            page.insert_text((rect.x0 + 5, rect.y0 + 15), cell, fontsize=10)
    page.insert_text(
        (72, 300),
        "EMEA growth was driven by the renewal of three enterprise contracts.",
        fontsize=11,
    )
    data = doc.tobytes()
    doc.close()
    return data


def _scanned_pdf() -> bytes:
    """Image-only: `get_text` returns nothing and one raster covers the page."""
    import pymupdf

    source = pymupdf.open()
    page = source.new_page()
    page.insert_text((72, 110), "INVOICE 2026-0431", fontsize=20)
    page.insert_text((72, 150), "Acme Corporation", fontsize=13)
    page.insert_text((72, 180), "Total due: USD 18,400.00", fontsize=13)
    page.insert_text((72, 210), "Payment terms: net 30 days.", fontsize=13)
    rendered = pymupdf.open(stream=source.tobytes(), filetype="pdf")
    source.close()

    out = pymupdf.open()
    for index in range(rendered.page_count):
        pixmap = rendered[index].get_pixmap(dpi=150)
        target = out.new_page(width=rendered[index].rect.width, height=rendered[index].rect.height)
        target.insert_image(target.rect, stream=pixmap.tobytes("png"))
    rendered.close()
    data = out.tobytes()
    out.close()
    return data


def _expenses_csv() -> bytes:
    lines = ["category,quarter,amount_usd,owner"]
    rows = [
        ("Travel", "Q3", "48250", "Operations"),
        ("Software", "Q3", "112400", "Engineering"),
        ("Recruitment", "Q3", "63900", "People"),
        ("Facilities", "Q3", "88150", "Operations"),
        ("Travel", "Q2", "51100", "Operations"),
        ("Software", "Q2", "104900", "Engineering"),
    ]
    lines += [",".join(row) for row in rows]
    return ("\n".join(lines) + "\n").encode("utf-8")


def _policy_markdown() -> bytes:
    return (
        b"# Acme Security Policy\n\n"
        b"## Access control\n\n"
        b"### Passwords\n\n"
        b"Passwords must be at least twelve characters. The password rotation policy is that "
        b"passwords are not rotated on a schedule; they are changed on suspicion of compromise.\n\n"
        b"### Multi-factor authentication\n\n"
        b"All administrative accounts require a second factor.\n\n"
        b"## Retention\n\n"
        b"Audit logs are retained indefinitely and are append-only. Request telemetry is "
        b"retained for ninety days.\n"
    )


_BUILDERS = {
    "table_pdf": _table_pdf,
    "scanned_pdf": _scanned_pdf,
    "expenses_csv": _expenses_csv,
    "policy_markdown": _policy_markdown,
}


def _build(name: str) -> bytes:
    return _BUILDERS[name]()


# --- the client ----------------------------------------------------------------------


@dataclass
class Api:
    base_url: str
    token: str | None = None
    client: httpx.Client = field(default_factory=lambda: httpx.Client(timeout=30.0))

    def _headers(self) -> dict[str, str]:
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}

    def login(self, email: str, password: str) -> str:
        resp = self.client.post(
            f"{self.base_url}/api/v1/auth/login", json={"email": email, "password": password}
        )
        if resp.status_code != 200:
            raise SeedError(f"login failed for {email}: {resp.status_code} {resp.text[:200]}")
        return str(resp.json()["access_token"])

    def get(self, path: str, **kwargs) -> httpx.Response:  # noqa: ANN003
        return self.client.get(f"{self.base_url}{path}", headers=self._headers(), **kwargs)

    def post(self, path: str, **kwargs) -> httpx.Response:  # noqa: ANN003
        return self.client.post(f"{self.base_url}{path}", headers=self._headers(), **kwargs)


class SeedError(RuntimeError):
    """Anything that should stop the run with a sentence a human can act on."""


# --- steps ---------------------------------------------------------------------------


def _ensure_user(api: Api, email: str, password: str) -> str:
    """Create the demo user, or accept the one already there.

    `display_name` is **not optional in practice**, whatever the schema says: T-110 found the
    realm's user profile requires `firstName`/`lastName`, and a user created without them can
    be created and then never log in (§8.9 - under backend-mediated ROPC there is no browser,
    so any required action is a permanent lockout).
    """
    resp = api.post(
        "/api/v1/users",
        json={
            "email": email,
            "password": password,
            "display_name": "Demo User",
            "role": "user",
        },
    )
    if resp.status_code in (200, 201):
        return "created"
    if resp.status_code == 409:
        return "already existed"
    raise SeedError(f"could not create {email}: {resp.status_code} {resp.text[:300]}")


def _upload(api: Api, doc: SeedDocument, payload: bytes) -> tuple[str, bool]:
    resp = api.post(
        "/api/v1/documents",
        files={"file": (doc.filename, io.BytesIO(payload), doc.content_type)},
        data={"scope": "global"},
    )
    if resp.status_code not in (200, 202):
        raise SeedError(f"upload of {doc.filename} failed: {resp.status_code} {resp.text[:300]}")
    body = resp.json()
    return str(body["document_id"]), bool(body.get("duplicate", False))


def _await_active(
    api: Api, document_id: str, filename: str, *, tolerate_failure: bool = False
) -> str:
    """Poll to a terminal state.

    `tolerate_failure` is the scan's: a deployment with recognition off answers
    `NO_EXTRACTABLE_TEXT` (R-34), which is correct behaviour rather than an error, and is the
    only reliable way to learn the *target's* configuration from here. The caller then removes
    the row, because a `FAILED` document nobody explained is the worst thing to leave in a
    corpus a manual is being written against.
    """
    deadline = time.monotonic() + INGEST_TIMEOUT_SECONDS
    last = "?"
    while time.monotonic() < deadline:
        resp = api.get(f"/api/v1/documents/{document_id}")
        if resp.status_code != 200:
            raise SeedError(f"{filename}: could not read status ({resp.status_code})")
        last = str(resp.json().get("status"))
        if last == "ACTIVE":
            return last
        if last == "FAILED":
            error = resp.json().get("latest_job_error_code") or "unknown"
            if tolerate_failure:
                return f"FAILED:{error}"
            raise SeedError(f"{filename} failed to ingest: {error}")
        time.sleep(INGEST_POLL_SECONDS)
    raise SeedError(
        f"{filename} stuck in {last} after {INGEST_TIMEOUT_SECONDS:.0f}s "
        "- is the arq worker running?"
    )


def _existing_titles(api: Api) -> set[str]:
    resp = api.get("/api/v1/conversations")
    if resp.status_code != 200:
        raise SeedError(f"could not list conversations: {resp.status_code}")
    return {str(row.get("title", "")) for row in resp.json()}


def _ask(api: Api, conversation_id: str, question: str) -> str:
    """Run one turn and return its outcome. Consumes the SSE stream to completion."""
    outcome = "unknown"
    with api.client.stream(
        "POST",
        f"{api.base_url}/api/v1/conversations/{conversation_id}/messages",
        headers=api._headers(),
        json={"query": question, "document_ids": []},
        timeout=TURN_TIMEOUT_SECONDS,
    ) as resp:
        if resp.status_code != 200:
            resp.read()
            raise SeedError(f"turn refused: {resp.status_code} {resp.text[:200]}")
        for line in resp.iter_lines():
            if not line.startswith("data:"):
                continue
            import json as _json

            frame = _json.loads(line[5:])
            if frame.get("event") == "done":
                outcome = str(frame["data"].get("outcome", "unknown"))
    return outcome


# --- preconditions -------------------------------------------------------------------


def _is_local(base_url: str) -> bool:
    return "localhost:8000" in base_url or "127.0.0.1:8000" in base_url


def _preflight(api: Api) -> list[str]:
    """Everything that would make the run fail slowly, checked up front.

    **The settings half is advisory and says so.** This process reads `backend/.env`, while
    `--base-url` may point at a container that was built from a different one - so the OCR and
    backend notes describe *this* configuration, not necessarily the one being seeded. The
    scan does not depend on getting that right: it is attempted either way, and a deployment
    with recognition off answers `NO_EXTRACTABLE_TEXT`, which `_run` reads as the answer.
    """
    notes: list[str] = []
    try:
        health = api.client.get(f"{api.base_url}/health/ready", timeout=10.0)
    except httpx.RequestError as exc:
        raise SeedError(
            f"no API at {api.base_url} - start it, or pass --base-url "
            f"(the containerised stack serves the edge on :8088). {exc}"
        ) from exc
    if health.status_code != 200:
        notes.append(f"readiness is {health.status_code}: {health.text[:200]}")

    where = "this process" if _is_local(api.base_url) else f"this process, NOT {api.base_url}"
    settings = get_settings()
    if not settings.parser.ocr_enabled:
        notes.append(
            f"PARSER_OCR_ENABLED is false in {where} - the scan may not be recognisable. "
            "Turning it on also needs the `ocr` compose profile running, and "
            "PARSER_OCR_BUDGET_SECONDS + OCR_TIMEOUT_SECONDS must stay under "
            "WORKER_JOB_TIMEOUT_SECONDS."
        )
    if settings.llm.backend != "openai":
        notes.append(
            f"LLM_BACKEND={settings.llm.backend} in {where} - answers may be synthetic. Fine as "
            "a smoke test, wrong as a source for documentation screenshots."
        )
    return notes


# --- commands ------------------------------------------------------------------------


def _plan(api: Api, demo_email: str) -> int:
    print(f"target        : {api.base_url}")
    print(f"demo user     : {demo_email}")
    print()
    print("documents (uploaded to the GLOBAL scope, re-runs dedup by checksum):")
    for doc in DOCUMENTS:
        payload = _build(doc.build)
        skip = " [attempted; removed if the target has recognition off]" if doc.needs_ocr else ""
        print(f"  {doc.filename:<28} {len(payload):>8,} bytes  {doc.why}{skip}")
    print()
    print("conversations (created only if the title is not already present):")
    for chat in CHATS:
        print(f"  {chat.title:<28} {len(chat.questions)} question(s)  - {chat.why}")
    print()
    for note in _preflight(api):
        print(f"note: {note}")
    print()
    print("nothing was written. `run --yes` to apply.")
    return 0


def _run(api: Api, demo_email: str, demo_password: str) -> int:
    notes = _preflight(api)
    for note in notes:
        print(f"note: {note}")

    print(f"\nuser  {demo_email}: {_ensure_user(api, demo_email, demo_password)}")
    api.token = api.login(demo_email, demo_password)
    print("      signed in as the demo user; everything below is owned by them")

    print("\ndocuments")
    seeded = 0
    for doc in DOCUMENTS:
        document_id, duplicate = _upload(api, doc, _build(doc.build))
        if duplicate:
            print(f"  {doc.filename:<28} already present")
            seeded += 1
            continue
        status = _await_active(api, document_id, doc.filename, tolerate_failure=doc.needs_ocr)
        if status.startswith("FAILED:"):
            # Recognition is off *in the target*, whatever this process's settings say.
            # The row is removed rather than left as an unexplained `FAILED` document in
            # a corpus a manual is being written against.
            api.client.delete(
                f"{api.base_url}/api/v1/documents/{document_id}", headers=api._headers()
            )
            print(
                f"  {doc.filename:<28} SKIPPED - {status.removeprefix('FAILED:')}; "
                "recognition is off in the target, so the row was removed"
            )
            continue
        print(f"  {doc.filename:<28} {status}")
        seeded += 1

    print("\nconversations")
    existing = _existing_titles(api)
    for chat in CHATS:
        if chat.title in existing:
            print(f"  {chat.title:<28} already present")
            continue
        resp = api.post("/api/v1/conversations", json={"title": chat.title})
        if resp.status_code != 201:
            raise SeedError(f"could not create {chat.title!r}: {resp.status_code}")
        conversation_id = resp.json()["id"]
        outcomes = [_ask(api, conversation_id, question) for question in chat.questions]
        print(f"  {chat.title:<28} {', '.join(outcomes)}")

    print(f"\nseeded {seeded} document(s) and {len(CHATS)} conversation(s) for {demo_email}.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tools.seed_demo",
        # NOT `__doc__`: the module docstring is deliberately typographic prose, and
        # `--help` goes to a console that may be cp1252 (R-80's finding). Prose keeps
        # its em dashes; stdout is ASCII.
        description="Seed a demo user, documents and answered chats (T-709).",
        epilog="Read tools/seed_demo.py for why this drives the HTTP API.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help=f"default {DEFAULT_BASE_URL}")
    parser.add_argument("--admin-email", required=True, help="an administrator, to create the user")
    parser.add_argument("--admin-password", required=True)
    parser.add_argument("--demo-email", default="demo@corpus.local")
    parser.add_argument("--demo-password", default="demo-Password-1")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("plan", help="describe what would be created (read-only)")
    run_cmd = sub.add_parser("run", help="create the demo user, documents and conversations")
    run_cmd.add_argument(
        "--yes",
        action="store_true",
        help="required: this creates a user and spends model calls",
    )

    args = parser.parse_args(argv)
    api = Api(base_url=args.base_url.rstrip("/"))

    try:
        api.token = api.login(args.admin_email, args.admin_password)
        if args.command == "plan":
            return _plan(api, args.demo_email)
        if not args.yes:
            print("refusing to run without --yes (it creates a user and spends model calls)")
            return 2
        return _run(api, args.demo_email, args.demo_password)
    except SeedError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    finally:
        api.client.close()


if __name__ == "__main__":  # pragma: no cover - exercised as a subprocess
    raise SystemExit(main())
