"""T-604 turn telemetry — the durable per-request record (NFR-OBS-01, R-79)

R-43(5) ruled there is no telemetry *table*, and that ruling stands where it was aimed: no
FR-ANL stats-panel card reads one, so NFR-OBS-02's "displayed counts match telemetry" is an
identity with the `messages` columns rather than an agreement between two stores. What it
deferred here is narrower and real — **a turn that fails writes nothing durable anywhere**.
R-54(3) keeps FR-ERR-04 copy out of `messages` (it would be charged against the NFR-CAP-01
budget R-51(4) derives from that table), so "telemetry logs request start/end/**failure**"
was satisfied by a log stream and by nothing that survives a restart.

**No foreign keys, deliberately.** `conversation_id`, `owner_id` and `message_id` are plain
UUIDs: an operator's record of what the system did must outlive the conversation whose
deletion is a user action, and an `ON DELETE CASCADE` would make error-rate and latency
history rewritable by the people it measures. The rows carry no payload text — ids, an
outcome, a failure class and four integers — and `TELEMETRY_RETENTION_DAYS` (NFR-OBS-04,
settled at 90 by R-79(3)) bounds how long they live.

Three indexes, all read-shaped: the retention sweep's `created_at`, one conversation's
history, and error-rate over time on `audit_log`'s `(event_type, created_at)` precedent.

Revision ID: 2ee964422ed2
Revises: c1a7f0e4b2d9
Create Date: 2026-08-16 17:58:31.058536
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ee964422ed2"
down_revision: str | None = "c1a7f0e4b2d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turn_telemetry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turn_telemetry")),
    )
    op.create_index(
        "ix_turn_telemetry_conversation_id_created_at",
        "turn_telemetry",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_turn_telemetry_created_at", "turn_telemetry", ["created_at"], unique=False)
    op.create_index(
        "ix_turn_telemetry_outcome_created_at",
        "turn_telemetry",
        ["outcome", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_turn_telemetry_outcome_created_at", table_name="turn_telemetry")
    op.drop_index("ix_turn_telemetry_created_at", table_name="turn_telemetry")
    op.drop_index("ix_turn_telemetry_conversation_id_created_at", table_name="turn_telemetry")
    op.drop_table("turn_telemetry")
    # ### end Alembic commands ###
