"""T-108 deterministic message and conversation ordering

Both halves of T-108 have the same root cause: `now()` is the **transaction** timestamp,
so rows written in one transaction share it exactly and any ordering built on it falls
through to a tiebreak on the random UUID `id`.

* `messages.seq` — a monotonic IDENTITY column replacing `(created_at, id)` as the
  intra-conversation display order. A chat turn writes the question and the answer in one
  transaction, so this was a coin flip on rendering them the wrong way round.
* `conversations.updated_at` — now defaults to `clock_timestamp()`, the real wall clock,
  which advances *within* a transaction. This column is the FR-SBR-03 sidebar order.

Backfill note: `ADD COLUMN … IDENTITY NOT NULL` assigns `seq` to existing rows in physical
order, which for already-stored messages is arbitrary but stable. Nothing in the product
has served a message list yet (the Messages API is T-402), so there is no ordering anyone
has seen to preserve.

The `onupdate=clock_timestamp()` half needs no DDL — SQLAlchemy renders it into the UPDATE
statement.

Revision ID: e05ce74039dd
Revises: 30bf0a62decc
Create Date: 2026-07-28 17:59:53.688493
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e05ce74039dd"
down_revision: str | None = "30bf0a62decc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False)
    )
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.create_index(
        "ix_messages_conversation_id_seq", "messages", ["conversation_id", "seq"], unique=False
    )
    # ### end Alembic commands ###
    # Not autogenerated: Alembic does not compare server defaults unless
    # `compare_server_default` is enabled in env.py.
    op.alter_column("conversations", "updated_at", server_default=sa.text("clock_timestamp()"))


def downgrade() -> None:
    op.alter_column("conversations", "updated_at", server_default=sa.text("now()"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_conversation_id_seq", table_name="messages")
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.drop_column("messages", "seq")
    # ### end Alembic commands ###
