"""T-208 partial per-KB checksum uniqueness (R-39(4))

`UNIQUE(knowledge_base_id, checksum_sha256)` covered every row including tombstones,
while `DocumentRepository.find_by_checksum` has always filtered `deleted_at IS NULL`.
Nothing wrote `deleted_at` before T-208, so the disagreement was invisible; the moment
FR-ING-05 deletion lands it becomes: the FR-KBM-08 fast path misses the deleted row, the
insert trips the constraint anyway, and T-202's dedup-race branch re-reads with the same
filter, finds no winner and raises — so re-uploading a file you previously deleted
returns **503**.

Replacing the constraint with a partial unique index makes the schema state exactly what
the query has always assumed. Deleted rows are retained by requirement (FR-ING-05 "marks
`DELETED` with a timestamp") and by `knowledge_jobs.document_id`'s foreign key, so
dropping the tombstone instead was never an option.

Hand-written rather than autogenerated: Alembic renders a constraint→partial-index swap
as an unqualified drop plus a plain index, silently losing the `WHERE` clause.

Revision ID: b41c7e9d0a52
Revises: e05ce74039dd
Create Date: 2026-07-28 19:30:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "b41c7e9d0a52"
down_revision: str | None = "e05ce74039dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CONSTRAINT = "uq_documents_knowledge_base_id_checksum_sha256"
_INDEX = "uq_documents_knowledge_base_id_checksum_sha256_live"


def upgrade() -> None:
    op.drop_constraint(_CONSTRAINT, "documents", type_="unique")
    op.create_index(
        _INDEX,
        "documents",
        ["knowledge_base_id", "checksum_sha256"],
        unique=True,
        postgresql_where=text("deleted_at IS NULL"),
    )


def downgrade() -> None:
    # The reverse is only valid while no two live-and-deleted rows share a checksum within
    # one knowledge base — i.e. before anything has been deleted and re-uploaded. That is
    # inherent to narrowing a uniqueness rule, not an oversight here.
    op.drop_index(_INDEX, table_name="documents")
    op.create_unique_constraint(_CONSTRAINT, "documents", ["knowledge_base_id", "checksum_sha256"])
