"""T-609 turn telemetry groundedness — the gate's own input, retained (OI-24, R-80(1))

The FR-CIT-06(4) gate scores every answer's structural coverage and `GATE_MIN_GROUNDEDNESS`
decides from it whether the answer is served or the turn abstains — and until now that score
was **retained nowhere**. R-49(1) keeps it out of `messages.evaluation` and off every user
surface, which is right and unchanged (a second number beside the DeepEval chips is OI-34's
two-measurements-one-reader problem), but the consequence was that the single threshold with
the most direct effect on what a user sees was the one no accumulated evidence could reach.
R-50(6) had already sanctioned keeping it as *internal signal* on `rag.eval.completed`; it
simply lived only as long as the log line.

Nullable, and left NULL for every row written before this: a turn that never reached the gate
(an error, an injection block) genuinely has no score, and backfilling a zero would claim a
measurement nobody took — which the calibration report would then read as a maximally
ungrounded answer.

Revision ID: 73a7dfdf7582
Revises: 2ee964422ed2
Create Date: 2026-08-16 19:15:09.774779
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73a7dfdf7582"
down_revision: str | None = "2ee964422ed2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("turn_telemetry", sa.Column("groundedness", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("turn_telemetry", "groundedness")
    # ### end Alembic commands ###
