"""add knowledge_jobs document_version

T-207 / R-38(1). The ingestion worker builds one specific
`document_chunks.document_version` and, per R-37(9), advances
`documents.current_version` to it in the swap transaction. It cannot read the target
*from* `current_version`: under R-36(3) a replace deliberately leaves that pointer on the
old version until the swap commits, so the old version keeps serving retrieval while the
new one is built. The target therefore travels on the job row.

`server_default=1` backfills existing rows correctly — every job written before this
migration was minted by T-202, which only ever ingests v1.

Revision ID: 30bf0a62decc
Revises: f77d3281a1fb
Create Date: 2026-07-28 16:22:56.567050
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30bf0a62decc"
down_revision: str | None = "f77d3281a1fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_jobs",
        sa.Column("document_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge_jobs", "document_version")
    # ### end Alembic commands ###
