"""T-302 processing locks — the R-24 per-user action gate (R-43)

One row per user: `owner_id` is the primary key, so the read every mutating document route
performs is a PK lookup. `expires_at` is the crash release and there is no sweeper — a row
left behind by a killed run is ignored by every reader and overwritten by the next turn.

No `AuditEventType` change ships with this: the FR-ORC-02 denial is filed under the existing
`AUTH` member with a `details.action` discriminator, which is how `record_auth` has always
multiplexed its five actions. That keeps this migration to one table and avoids
hand-writing a CHECK-constraint swap for a `native_enum=False` column.

Revision ID: 0ff884b4781a
Revises: b41c7e9d0a52
Create Date: 2026-07-29 23:52:26.315301
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ff884b4781a"
down_revision: str | None = "b41c7e9d0a52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_locks",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_processing_locks_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_processing_locks_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("owner_id", name=op.f("pk_processing_locks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processing_locks")
    # ### end Alembic commands ###
