"""Correlation ids for the log stream (NFR-OBS-01, T-604, R-79(2)).

**The problem this solves.** Before T-604 a turn emitted `graph.turn.start`, then
`rag.router.classified`, `security.injection.suspicious`, `rag.rerank.completed`,
`rag.search.*`, `graph.node_failed` and finally `graph.turn.end` — and **only the first and
last carried the conversation id**. Every event in between named its own subject and
nothing else, so the log stream could tell you *that* a router call was slow and never
*which turn* it belonged to. That is not a missing field on eight call sites; it is the
difference between a log stream and a trace, and adding the ids by hand to each emitter
would have to be redone for every emitter added afterwards.

`structlog.contextvars` binds them once per turn and every subsequent event in the same
task inherits them, including ones written after this module was last edited. The binding
is `contextvars`-based, so concurrent turns — each an asyncio task, one per request — cannot
see each other's ids.

**Two scopes, deliberately not one.**

* :func:`bound_turn` — the FR-ORC-01 turn. Its key is `(conversation_id, turn_index)`, not
  a freshly minted run id, because that pair is the one identifier that is **stable across a
  resume**: a run id would be regenerated by the process that picks the turn back up, which
  is precisely the case an operator is trying to follow. It is also exactly the key the
  durable `turn_telemetry` row carries, so the log stream and the table join without a
  translation step.
* :func:`bound_request` — the HTTP request. A graph run outlives its request (streaming,
  and on resume it has none at all — `RAGContext` holds a `sessionmaker` rather than a
  session for the same reason), so the request id **cannot** be the turn's key. They nest:
  a turn started by a request carries both.

Both are context managers that restore the previous binding on exit rather than clearing
it, so a nested scope cannot erase its parent's ids.
"""

from __future__ import annotations

import uuid
from collections.abc import Awaitable, Callable, Iterator
from contextlib import contextmanager
from typing import TYPE_CHECKING

import structlog

if TYPE_CHECKING:  # pragma: no cover - import cycle avoidance only
    from starlette.requests import Request
    from starlette.responses import Response

__all__ = [
    "REQUEST_ID_HEADER",
    "bound_request",
    "bound_turn",
    "new_request_id",
    "request_context_middleware",
]

#: Echoed on every response so a user reporting a problem can quote one string that appears
#: on every log line the request produced. Accepted on the way in too — a proxy or a load
#: test that already has an id keeps it, which is what makes the id useful across hops.
REQUEST_ID_HEADER = "X-Request-ID"


def new_request_id() -> str:
    """A fresh correlation id. `uuid4().hex` — short enough to quote over the phone."""
    return uuid.uuid4().hex


@contextmanager
def bound_turn(*, conversation_id: uuid.UUID | str, turn_index: int | None) -> Iterator[None]:
    """Bind the turn's ids for the duration of the block.

    Note that `structlog.contextvars.bound_contextvars` restores the previous values on
    exit rather than deleting them, which matters for the regenerate path: a second turn
    inside one request must not leave the first turn's `turn_index` bound behind it.
    """
    with structlog.contextvars.bound_contextvars(
        conversation_id=str(conversation_id), turn_index=turn_index
    ):
        yield


@contextmanager
def bound_request(*, request_id: str, method: str, path: str) -> Iterator[None]:
    """Bind the HTTP request's correlation id and its route for the duration of the block.

    `method` and `path` ride along because a bare id is only useful once you already have a
    line that names the route — with them, one grep on `request_id` is a complete account of
    what the request did. The path is the **URL path**, never the query string: a query
    string can carry a document id, a filter, or (on a route someone adds later) text, and
    R-43(5)'s no-payload rule is cheaper to keep structurally than to police per route.
    """
    with structlog.contextvars.bound_contextvars(
        request_id=request_id, http_method=method, http_path=path
    ):
        yield


async def request_context_middleware(
    request: Request, call_next: Callable[[Request], Awaitable[Response]]
) -> Response:
    """Bind a correlation id for the request and echo it on the response.

    An inbound `X-Request-ID` is **honoured rather than replaced**, so an id assigned by a
    proxy, a load test or the GUI survives the hop — that is the whole point of the header.
    It is validated first, because it is attacker-controlled and it ends up in a log line: an
    unbounded value is a log-flooding primitive, and a newline in it is log injection
    (structlog's `JSONRenderer` escapes control characters, so this is defence in depth rather
    than the only control).

    An id that fails validation is **replaced, never repaired**. Truncating an over-long one
    would keep a value that is no longer the caller's id — correlating against the upstream
    system it came from would then quietly fail, which is worse than plainly minting a new
    id and saying so in the response header.

    Nothing here logs an event of its own. Access logging is uvicorn's, and adding a second
    line per request would double the log volume to say what the server already says; this
    middleware exists so that *the lines that already exist* can be joined.
    """
    supplied = request.headers.get(REQUEST_ID_HEADER, "")
    request_id = _sanitize_request_id(supplied) or new_request_id()
    with bound_request(request_id=request_id, method=request.method, path=request.url.path):
        response = await call_next(request)
    response.headers[REQUEST_ID_HEADER] = request_id
    return response


#: Long enough for a UUID in any spelling, short enough that a log line stays a log line.
_MAX_REQUEST_ID_CHARS = 64
_ID_ALPHABET = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.")


def _sanitize_request_id(value: str) -> str:
    """Keep an inbound id only if it is already the shape of an id — never repair one."""
    trimmed = value.strip()
    if not trimmed or len(trimmed) > _MAX_REQUEST_ID_CHARS:
        return ""
    if any(character not in _ID_ALPHABET for character in trimmed):
        return ""
    return trimmed
